apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-demo
  template:
    metadata:
      labels:
        app: devsecops-demo
    spec:
      containers:
      - name: app
        image: trevorgray1985/devsecops-demo:latest
        ports:
        - containerPort: 5000
