apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-app.fullname" . }}
  labels:
    app: {{ include "example-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "example-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "example-app.name" . }}
    spec:
      serviceAccountName: {{ include "example-app.fullname" . }}
      containers:
        - name: {{ include "example-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: EXAMPLE_KEY
              value: {{ .Values.env.EXAMPLE_KEY | quote }}
